name: Build ViridiKeyboard Firmware


on:
push:
branches: [ main ]
pull_request:
workflow_dispatch:


jobs:
build:
uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
with:
board: "nice_nano_v2"
shield: "ViridiKeyboard"
config-path: "config"
