name: Build ZMK firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@develop
    with:
      shield: "ViridiKeyboard"
      board: "nice_nano_v2"
      artifact-name: "ViridiKeyboard-nice_nano_v2-zmk"
