name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup ZMK
        run: |
          west init -l config
          west update
          
      - name: Build Firmware
        run: |
          docker run --rm -v $PWD:/workspace \
            -w /workspace zmkfirmware/zmk-build-arm:stable \
            bash -c "west build -b nice_nano_v2 --pristine -- \
              -DSHIELD=ViridiKeyboard \
              -DZMK_CONFIG=/workspace/config \
              -DSHIELD_DIR=/workspace/boards/shields"
              
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ViridiKeyboard-firmware
          path: build/zephyr/*.uf2
