name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          docker run --rm -v $PWD:/workspace \
            -w /workspace zmkfirmware/zmk-build-arm:stable \
            bash -c "
            git config --global --add safe.directory '*' &&
            west init --mr v0.3.0 -l config &&
            west update &&
            west build -b nice_nano_v2 --pristine -- \
              -DSHIELD=ViridiKeyboard \
              -DZMK_CONFIG=/workspace/config \
              -DSHIELD_DIR=/workspace/boards/shields
            "

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/*.uf2
